workflows:

  atomus-parent:
    name: Atomus Parent Simulator Build

    instance_type: mac_mini_m2

    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17

      groups:
        - firebase_parent

    scripts:
      - name: Flutter Clean
        script: |
          flutter clean

      - name: Install Flutter Packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS Simulator App
        script: |
          flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app



  atomus-teacher:
    name: Atomus Teacher Simulator Build

    instance_type: mac_mini_m2

    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17

      groups:
        - firebase_teacher

    scripts:
      - name: Flutter Clean
        script: |
          flutter clean

      - name: Install Flutter Packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS Simulator App
        script: |
          flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app



  atomus-admin:
    name: Atomus Admin Simulator Build

    instance_type: mac_mini_m2

    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17

      groups:
        - firebase_admin

    scripts:
      - name: Flutter Clean
        script: |
          flutter clean

      - name: Install Flutter Packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS Simulator App
        script: |
          flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app