class StudentInfo {
  final String id;
  final String fullName;
  final String? admissionNumber;
  final String? rollNumber;
  final String? gender;
  final String? dateOfBirth;
  final String? grade;
  final double attendancePercentage;
  final String? progressStatus;
  final String? email;
  final String? phoneNumber;
  final String? relationship;

  /// Google Drive file ID for the student's profile photo.
  /// Stored as a raw Drive ID — URL is generated by DriveImageHelper.
  final String? profilePhotoDriveId;

  final String? courseId;
  final String? campusId;
  final String? campusName;
  final String? paymentQrUrl;
  final String? paymentQrDriveId;

  StudentInfo({
    required this.id,
    required this.fullName,
    this.admissionNumber,
    this.rollNumber,
    this.gender,
    this.dateOfBirth,
    this.grade,
    this.attendancePercentage = 0.0,
    this.progressStatus = 'Average',
    this.email,
    this.phoneNumber,
    this.relationship,
    this.profilePhotoDriveId,
    this.courseId,
    this.campusId,
    this.campusName,
    this.paymentQrUrl,
    this.paymentQrDriveId,
    @Deprecated('Use profilePhotoDriveId') String? avatarUrl,
  });

  factory StudentInfo.fromMap(Map<String, dynamic> map) {
    final campusesRaw = map['campuses'];
    Map<String, dynamic>? campusesMap;
    if (campusesRaw is Map) {
      campusesMap = Map<String, dynamic>.from(campusesRaw);
    } else if (campusesRaw is List && campusesRaw.isNotEmpty) {
      campusesMap = Map<String, dynamic>.from(campusesRaw.first);
    }

    return StudentInfo(
      id: map['id'] ?? '',
      fullName: map['full_name'] ?? '',
      admissionNumber: map['admission_number']?.toString(),
      rollNumber: map['roll_number']?.toString(),
      gender: map['gender'],
      dateOfBirth: map['date_of_birth']?.toString(),
      grade: map['grade'],
      attendancePercentage: (map['attendance_percentage'] ?? 0.0).toDouble(),
      progressStatus: map['progress_status'] ?? 'Average',
      email: map['email'],
      phoneNumber: map['phone_number']?.toString(),
      relationship: map['relationship'],
      profilePhotoDriveId: map['profile_photo_drive_id']?.toString(),
      courseId: map['course_id']?.toString(),
      campusId: map['campus_id']?.toString(),
      campusName: campusesMap?['name']?.toString() ?? map['campus_name']?.toString(),
      paymentQrUrl: () {
        final url = campusesMap?['payment_qr_url']?.toString() ?? map['payment_qr_url']?.toString();
        if (url == null || url.isEmpty) return null;
        // Only keep full absolute URLs (https://...) — discard relative
        // server paths like /uploads/... which only work on localhost.
        if (url.startsWith('http://') || url.startsWith('https://')) {
          return url;
        }
        return null;
      }(),
      paymentQrDriveId: () {
        // 1. Direct Drive ID from the campus record
        final driveId = campusesMap?['payment_qr_drive_id']?.toString()
            ?? map['payment_qr_drive_id']?.toString();
        if (driveId != null && driveId.isNotEmpty && RegExp(r'^[A-Za-z0-9_\-]{10,60}$').hasMatch(driveId)) {
          return driveId;
        }
        // 2. Try to extract a Drive ID from the URL (e.g. /api/media?id=DRIVE_ID)
        final url = campusesMap?['payment_qr_url']?.toString() ?? map['payment_qr_url']?.toString();
        if (url != null && url.contains('id=')) {
          final idMatch = RegExp(r'[?&]id=([A-Za-z0-9_\-]{10,60})').firstMatch(url);
          if (idMatch != null) return idMatch.group(1);
        }
        return null;
      }(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'full_name': fullName,
      'gender': gender,
      'date_of_birth': dateOfBirth,
      'email': email,
      'phone_number': phoneNumber != null
          ? double.tryParse(phoneNumber!)
          : null,
      'relationship': relationship,
      'course_id': courseId,
    };
  }

  String get name => fullName;
  double get overallProgress => attendancePercentage / 100.0;

  /// Initials used for avatar placeholder when no Drive photo is set.
  String get initials {
    final parts = fullName.trim().split(' ');
    if (parts.length >= 2) {
      return '${parts.first[0]}${parts.last[0]}'.toUpperCase();
    }
    return fullName.isNotEmpty ? fullName[0].toUpperCase() : '?';
  }
}

class ExamMark {
  final String subject;
  final int marksObtained;
  final int totalMarks;
  final String grade;
  final String? subjectId;

  ExamMark({
    required this.subject,
    required this.marksObtained,
    required this.totalMarks,
    required this.grade,
    this.subjectId,
  });

  factory ExamMark.fromMap(Map<String, dynamic> map) {
    final marksObtained = (map['marks_obtained'] ?? 0).toInt();
    final totalMarks = (map['total_marks'] ?? 100).toInt();
    
    String calculatedGrade;
    if (totalMarks <= 0) {
      calculatedGrade = 'N/A';
    } else {
      final percentage = (marksObtained / totalMarks) * 100;
      if (percentage >= 90) {
        calculatedGrade = 'A+';
      } else if (percentage >= 80) {
        calculatedGrade = 'A';
      } else if (percentage >= 70) {
        calculatedGrade = 'B+';
      } else if (percentage >= 60) {
        calculatedGrade = 'B';
      } else if (percentage >= 50) {
        calculatedGrade = 'C';
      } else {
        calculatedGrade = 'F';
      }
    }

    return ExamMark(
      subject:
          map['subjects']?['name'] ??
          map['subjects']?['subject_name'] ??
          map['subject_name'] ??
          'General',
      marksObtained: marksObtained,
      totalMarks: totalMarks,
      grade: calculatedGrade,
      subjectId: map['subject_id']?.toString(),
    );
  }
}

class ExamSession {
  final String title;
  final String date;
  final List<ExamMark> subjects;
  final bool isDaily;

  ExamSession({
    required this.title,
    required this.date,
    required this.subjects,
    this.isDaily = false,
  });

  factory ExamSession.fromMap(
    Map<String, dynamic> map,
    List<ExamMark> subjects,
  ) {
    final examData = map['exams'] ?? map;
    final isDaily = examData['is_daily'] as bool? ?? false;
    final dateVal = isDaily
        ? (map['mark_date']?.toString() ?? examData['exam_date']?.toString() ?? 'N/A')
        : (examData['exam_date']?.toString() ?? 'N/A');
    return ExamSession(
      title: examData['name'] ?? examData['title'] ?? 'Examination',
      date: dateVal,
      subjects: subjects,
      isDaily: isDaily,
    );
  }
}

class AttendanceRecord {
  final String id;
  final String studentId;
  final String? batchId;
  final String? courseId;
  final String? subjectId;
  final DateTime date;
  final String status; // 'Present', 'Absent', 'Late'
  final int? periodNumber;
  final String? markerName;
  final String? markerRole;
  final String? subjectName;

  AttendanceRecord({
    required this.id,
    required this.studentId,
    this.batchId,
    this.courseId,
    this.subjectId,
    required this.date,
    required this.status,
    this.periodNumber,
    this.markerName,
    this.markerRole,
    this.subjectName,
  });

  bool get isPresent => status == 'Present' || status == 'Late';

  factory AttendanceRecord.fromMap(Map<String, dynamic> map) {
    final subject = map['subjects'] as Map<String, dynamic>?;
    return AttendanceRecord(
      id: map['id'].toString(),
      studentId: map['student_id'] ?? '',
      batchId: map['batch_id'],
      courseId: map['course_id'],
      subjectId: map['subject_id'],
      date: DateTime.parse(
        map['attendance_date'] ?? DateTime.now().toIso8601String(),
      ),
      status: map['status'] ?? 'Absent',
      periodNumber: map['period_number'] != null
          ? int.tryParse(map['period_number'].toString())
          : null,
      markerName: map['attendance_marker_name'],
      markerRole: map['attendance_marker_role'],
      subjectName: subject?['name'] ?? map['subject_name'],
    );
  }
}

class FeeRecord {
  final String title;
  final double amount;
  final DateTime dueDate;
  final bool isPaid;
  final String receiptId;
  final String? id;
  final double? amountPaid;
  final String? status;
  final DateTime? paymentDate;

  FeeRecord({
    required this.title,
    required this.amount,
    required this.dueDate,
    required this.isPaid,
    this.receiptId = '',
    this.id,
    this.amountPaid,
    this.status,
    this.paymentDate,
  });
}

class Announcement {
  final String id;
  final String title;
  final String description;

  /// Direct URL to the announcement image/poster.
  final String? imageUrl;

  /// Google Drive file ID for the announcement image/poster.
  /// Use DriveImageHelper to generate the display URL.
  final String? imageDriveId;

  final String type;
  final String targetAudience;
  final String? courseId;
  final String? batchId;
  final bool isPopup;
  final bool isActive;
  final DateTime startDate;
  final DateTime? endDate;
  final DateTime createdAt;

  Announcement({
    required this.id,
    required this.title,
    required this.description,
    this.imageUrl,
    this.imageDriveId,
    this.type = 'General Announcement',
    this.targetAudience = 'All',
    this.courseId,
    this.batchId,
    this.isPopup = false,
    this.isActive = true,
    required this.startDate,
    this.endDate,
    required this.createdAt,
  });

  int get priority => type == 'Urgent' ? 10 : 0;
  bool get hasImage =>
      (imageDriveId != null && imageDriveId!.isNotEmpty) ||
      (imageUrl != null && imageUrl!.isNotEmpty);

  factory Announcement.fromMap(Map<String, dynamic> map) {
    return Announcement(
      id: map['id'].toString(),
      title: map['title'] ?? '',
      description: map['description'] ?? '',
      imageUrl: map['image_url']?.toString(),
      imageDriveId: map['image_drive_id']?.toString(),
      type: map['type'] ?? 'General Announcement',
      targetAudience: map['target_audience'] ?? 'All',
      courseId: map['course_id']?.toString(),
      batchId: map['batch_id']?.toString(),
      isPopup: map['is_popup'] ?? false,
      isActive: map['is_active'] ?? true,
      startDate: DateTime.parse(
        map['start_date'] ?? DateTime.now().toIso8601String(),
      ),
      endDate: map['end_date'] != null ? DateTime.parse(map['end_date']) : null,
      createdAt: DateTime.parse(
        map['created_at'] ?? DateTime.now().toIso8601String(),
      ),
    );
  }
}

class Course {
  final String id;
  final String name;
  final String? description;
  final int? durationMonths;
  final String courseType;
  final String? classLevel;
  final double feeAmount;
  final String mode;

  /// Google Drive file ID for the course thumbnail.
  /// Use DriveImageHelper to generate the display URL.
  final String? thumbnailDriveId;

  final bool isActive;

  Course({
    required this.id,
    required this.name,
    this.description,
    this.durationMonths,
    required this.courseType,
    this.classLevel,
    required this.feeAmount,
    required this.mode,
    this.thumbnailDriveId,
    required this.isActive,
    @Deprecated('Use thumbnailDriveId') String? thumbnailUrl,
  });

  factory Course.fromMap(Map<String, dynamic> map) {
    return Course(
      id: map['id']?.toString() ?? '',
      name: map['name'] ?? '',
      description: map['description'],
      durationMonths: map['duration_months'] != null
          ? (map['duration_months'] as num).toInt()
          : null,
      courseType: map['course_type'] ?? 'Regular',
      classLevel: map['class_level'],
      feeAmount: (map['fee_amount'] ?? 0.0).toDouble(),
      mode: map['mode'] ?? 'Offline',
      thumbnailDriveId: map['thumbnail_drive_id']?.toString(),
      isActive: map['is_active'] ?? true,
    );
  }
}

class Subject {
  final String id;
  final String? courseId;
  final String name;
  final String? subjectCode;
  final String? subjectType;
  final String? classLevel;
  final bool isActive;

  Subject({
    required this.id,
    this.courseId,
    required this.name,
    this.subjectCode,
    this.subjectType,
    this.classLevel,
    this.isActive = true,
  });

  factory Subject.fromMap(Map<String, dynamic> map) {
    return Subject(
      id: map['id']?.toString() ?? '',
      courseId: map['course_id']?.toString(),
      name: map['name'] ?? '',
      subjectCode: map['subject_code'],
      subjectType: map['subject_type'],
      classLevel: map['class_level'],
      isActive: map['is_active'] ?? true,
    );
  }
}
